name: Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx myst-parser sphinx-rtd-theme linkify-it-py

      - name: Build Sphinx
        working-directory: docs
        run: |
          export LANG=C.UTF-8
          export LC_ALL=C.UTF-8
          bash build.sh

      - name: Disable Jekyll
        run: |
          touch docs/_build/html/.nojekyll

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4